name: "Google Cloud Functions deploy action"
description: "Setup gcloud auth and deploy HTTP-triggered function using gcloud"
inputs:
  service_account_key:
    description: "Google Service Key"
    required: true
    default: ""
  project:
    description: "Google Project"
    required: true
  name:
    description: "Cloud Function name"
    required: true
  region:
    description: "Google Region"
    required: true
  runtime:
    description: "Cloud funtion's runtime"
    required: true
    default: "python38"
  entry_point:
    description: "Cloud funtion's entry point function"
    required: true
    default: "run"
  service_account:
    description: "Service account e-mail that Cloud function will use"
    required: true
    default: "run"
  env_vars:
    description: "Runtime environment variables to insert"
    required: false
    default: ""
  allow_unauthenticated:
    description: "Allow unauthenticated requests"
    required: false
    default: true
  vpc_connector:
    description: "Which VPC connector to use"
    required: false
    default: ""
  max_instances:
    description: "Max concurrent instances"
    required: false
    default: "1"
  memory:
    description: "Limit of the amount of memory the function can use"
    required: false
    default: "128MB"
  timeout:
    description: "Timeout for the Cloud function (defaults to 30s)"
    required: false
    default: "30"
  egress_settings:
    description: "Egress settings (private-ranges-only|all) "
    required: false
    default: "private-ranges-only"
  ingress_settings:
    description: "Ingress settings (internal-and-gclb|internal-only|all) "
    required: false
    default: "internal-and-gclb"
  trigger_type:
    description: "Trigger type (http|pubsub)"
    required: true
    default: "http"
    deprecationMessage: "Input trigger_type is deprecated. If inputs.trigger_topic is not specified, a HTTP-triggered GCF is deployed"
  trigger_topic:
    description: "Trigger topic (creates subscription if it doesn't exist)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Authenticate with Google Cloud
      shell: bash
      run: |
        echo ${{ inputs.service_account_key }} | base64 -d > /tmp/key.json
        gcloud auth activate-service-account --key-file=/tmp/key.json

    - name: Configure project and region
      shell: bash
      run: |
        gcloud --quiet config set project ${{ inputs.project }}
        gcloud --quiet config set compute/region ${{ inputs.region }}

    - name: Deploy Google Cloud Function
      shell: bash
      run: |
        CMD="gcloud --quiet functions deploy ${{ inputs.name }} \
        --region ${{ inputs.region }} \
        --entry-point ${{ inputs.entry_point }} \
        --ingress-settings ${{ inputs.ingress_settings }} \
        --memory ${{ inputs.memory }} \
        --runtime ${{ inputs.runtime }} \
        --service-account ${{ inputs.service_account }} \
        --timeout ${{ inputs.timeout }} \
        --max-instances ${{ inputs.max_instances }}"

        if [ "${{ inputs.vpc_connector }}" != "" ]; then
          CMD="$CMD --vpc-connector ${{ inputs.vpc_connector }} \
          --egress-settings ${{ inputs.egress_settings }}"
        fi

        if [ "${{ inputs.env_vars }}" != "" ]; then
          CMD="$CMD --set-env-vars ${{ inputs.env_vars }}"
        fi

        if [ ${{ inputs.allow_unauthenticated }} == true ]; then
          CMD="$CMD --allow-unauthenticated"
        fi

        if [ "${{ inputs.trigger_topic }}" != "" ]; then
          CMD="$CMD --trigger-topic ${{ inputs.trigger_topic }}"
        else 
          CMD="$CMD --trigger-http"
        fi

        $CMD